# Generated by Django 5.2.15 on 2026-07-27 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_add_cluster_review_ticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="ticket",
            new_name="cluster_ticket",
        ),
        migrations.AddField(
            model_name="clusterreviewticket",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
