# Generated by Django 5.2.15 on 2026-07-28 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_cluster_ticket_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='batch',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='trigger',
            field=models.CharField(choices=[('upload', 'Upload'), ('cluster review', 'Cluster Review'), ('adjudication', 'Adjudication')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
