# Generated by Django 5.2.15 on 2026-07-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_remove_conversation_batch_alter_conversation_trigger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='discarded',
        ),
    ]
