# Generated by Django 5.2.15 on 2026-08-04 09:27

import time
import uuid

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import Count

import id_dedup.workflow.models


def dedupe_source_images(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:  # noqa: ARG001
    """
    Rename duplicate source_image values so the unique constraint can be added.

    A dirty dev DB may hold two rows whose source_image points at the same stored
    name (one overwrote the other). Keep the oldest row's value; move each
    duplicate's file to a time_ns-suffixed name and point the row at it. Rows
    whose file is already missing from storage are fixed on the DB value only.
    """
    Image = apps.get_model("workflow", "Image")
    dup_names = (
        Image.objects.values("source_image")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("source_image", flat=True)
    )
    for name in dup_names:
        rows = list(Image.objects.filter(source_image=name).order_by("created_at", "id"))
        for row in rows[1:]:
            field = row.source_image
            stem, dot, ext = field.name.rpartition(".")
            new_name = f"{stem}_{time.time_ns()}{dot}{ext}" if dot else f"{field.name}_{time.time_ns()}"
            try:
                field.save(new_name, field)
            except Exception:  # noqa: BLE001 - file gone from storage; fix the DB value only
                Image.objects.filter(pk=row.pk).update(source_image=new_name)


class Migration(migrations.Migration):
    """OutboxMessage schema, source_image uniqueness (with dedupe), index renames."""

    dependencies = [
        ("workflow", "0006_remove_discarded_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("max_attempts", models.PositiveIntegerField(default=id_dedup.workflow.models._default_max_attempts)),
                ("dead_lettered_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="identity",
            new_name="workflow_identity_centroid_idx",
            old_name="wf_identity_centroid_idx",
        ),
        migrations.RenameIndex(
            model_name="image",
            new_name="workflow_embedding_idx",
            old_name="wf_embedding_idx",
        ),
        migrations.RunPython(dedupe_source_images, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(fields=("source_image",), name="image_source_image_unique"),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["dispatched_at", "dead_lettered_at", "attempts", "created_at"],
                name="outbox_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="outbox_max_attempts_positive",
            ),
        ),
    ]
