# Generated by Django 5.2.15 on 2026-08-10 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the skipped-files audit trail to Batch."""

    dependencies = [
        ('workflow', '0007_outboxmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='skipped_files',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1024),
                blank=True,
                default=list,
                help_text='Names of uploaded files rejected at registration; an audit trail.',
                size=None,
            ),
        ),
    ]
