# Generated by Django 5.2.15 on 2026-08-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_batch_skipped_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'identities'},
        ),
    ]
