# Generated by Django 5.2.15 on 2026-06-18 13:12

from django.db import migrations
from pgvector import django as djvector


class Migration(migrations.Migration):  # noqa
    operations = [
        djvector.VectorExtension(),
    ]
