# Generated by Django 5.2.15 on 2026-07-16 11:38

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dedup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('centroid', pgvector.django.vector.VectorField(dimensions=512, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['centroid'], name='identity_centroid_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('source_image', models.FileField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='dedup.identity')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['embedding'], name='embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
